env:
  browser: true
  es2021: true
extends: ["airbnb-base", "plugin:prettier/recommended"]
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-await-in-loop:
    - warn
  radix:
    - error
    - as-needed
  default-param-last:
    - warn
  no-underscore-dangle: "off"
  no-param-reassign:
    - warn
  class-methods-use-this:
    - warn
  no-unused-vars:
    - warn
  no-nested-ternary: "off"
  no-restricted-syntax:
    - warn
    - selector: ForInStatement
      message:
        for..in loops iterate over the entire prototype chain, which is virtually
        never what you want. Use Object.{keys,values,entries}, and iterate over the
        resulting array.
    - selector: LabeledStatement
      message:
        Labels are a form of GOTO; using them makes code confusing and hard to
        maintain and understand.
    - selector: WithStatement
      message:
        "`with` is disallowed in strict mode because it makes code impossible
        to predict and optimize."
  import/extensions:
    - warn
    - always
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
globals:
  $: readonly
  ActiveEffect: readonly
  Actor: readonly
  CONFIG: readonly
  ChatMessage: readonly
  Combat: readonly
  Combatant: readonly
  Dialog: readonly
  DiceTerm: readonly
  Die: readonly
  FormDataExtended: readonly
  Handlebars: readonly
  Hooks: readonly
  Item: readonly
  Macro: readonly
  Roll: readonly
  TextEditor: readonly
  canvas: readonly
  duplicate: readonly
  foundry: readonly
  fromUuidSync: readonly
  game: readonly
  globals: readonly
  keyboard: readonly
  mergeObject: readonly
  renderTemplate: readonly
  setProperty: readonly
  ui: readonly
settings:
  import/extensions:
    - ".js"
